const artNames = [
  "academic painting",
  "amazing painting",
  "ancient statue",
  "basic painting",
  "beautiful statue",
  "calm painting",
  "common painting",
  "detailed painting",
  "dynamic painting",
  "familiar statue",
  "famous painting",
  "flowery painting",
  "gallant statue",
  "glowing painting",
  "graceful painting",
  "great statue",
  "informative statue",
  "jolly painting",
  "moody painting",
  "motherly statue",
  "moving painting",
  "mysterious painting",
  "mystic statue",
  "nice painting",
  "perfect painting",
  "proper painting",
  "quaint painting",
  "robust statue",
  "rock-head statue",
  "scary painting",
  "scenic painting",
  "serene painting",
  "sinking painting",
  "solemn painting",
  "tremendous statue",
  "twinkling painting",
  "valiant statue",
  "warm painting",
  "warrior statue",
  "wild painting left half",
  "wild painting right half",
  "wistful painting",
  "worthy painting",
] as const;

type ArtName = (typeof artNames)[number];

export const artOriginalTitleKoMap: Record<ArtName, string> = {
  "academic painting": "",
  "amazing painting": "",
  "ancient statue": "",
  "basic painting": "",
  "beautiful statue": "",
  "calm painting": "",
  "common painting": "",
  "detailed painting": "",
  "dynamic painting": "",
  "familiar statue": "",
  "famous painting": "",
  "flowery painting": "",
  "gallant statue": "",
  "glowing painting": "",
  "graceful painting": "",
  "great statue": "",
  "informative statue": "",
  "jolly painting": "",
  "moody painting": "",
  "motherly statue": "",
  "moving painting": "",
  "mysterious painting": "",
  "mystic statue": "",
  "nice painting": "",
  "perfect painting": "",
  "proper painting": "",
  "quaint painting": "",
  "robust statue": "",
  "rock-head statue": "",
  "scary painting": "",
  "scenic painting": "",
  "serene painting": "",
  "sinking painting": "",
  "solemn painting": "",
  "tremendous statue": "",
  "twinkling painting": "",
  "valiant statue": "",
  "warm painting": "",
  "warrior statue": "",
  "wild painting left half": "",
  "wild painting right half": "",
  "wistful painting": "",
  "worthy painting": "",
};

export const artAuthorKoMap: Record<ArtName, string> = {
  "academic painting": "",
  "amazing painting": "",
  "ancient statue": "",
  "basic painting": "",
  "beautiful statue": "",
  "calm painting": "",
  "common painting": "",
  "detailed painting": "",
  "dynamic painting": "",
  "familiar statue": "",
  "famous painting": "",
  "flowery painting": "",
  "gallant statue": "",
  "glowing painting": "",
  "graceful painting": "",
  "great statue": "",
  "informative statue": "",
  "jolly painting": "",
  "moody painting": "",
  "motherly statue": "",
  "moving painting": "",
  "mysterious painting": "",
  "mystic statue": "",
  "nice painting": "",
  "perfect painting": "",
  "proper painting": "",
  "quaint painting": "",
  "robust statue": "",
  "rock-head statue": "",
  "scary painting": "",
  "scenic painting": "",
  "serene painting": "",
  "sinking painting": "",
  "solemn painting": "",
  "tremendous statue": "",
  "twinkling painting": "",
  "valiant statue": "",
  "warm painting": "",
  "warrior statue": "",
  "wild painting left half": "",
  "wild painting right half": "",
  "wistful painting": "",
  "worthy painting": "",
};

export const artStyleKoMap: Record<ArtName, string> = {
  "academic painting": "",
  "amazing painting": "",
  "ancient statue": "",
  "basic painting": "",
  "beautiful statue": "",
  "calm painting": "",
  "common painting": "",
  "detailed painting": "",
  "dynamic painting": "",
  "familiar statue": "",
  "famous painting": "",
  "flowery painting": "",
  "gallant statue": "",
  "glowing painting": "",
  "graceful painting": "",
  "great statue": "",
  "informative statue": "",
  "jolly painting": "",
  "moody painting": "",
  "motherly statue": "",
  "moving painting": "",
  "mysterious painting": "",
  "mystic statue": "",
  "nice painting": "",
  "perfect painting": "",
  "proper painting": "",
  "quaint painting": "",
  "robust statue": "",
  "rock-head statue": "",
  "scary painting": "",
  "scenic painting": "",
  "serene painting": "",
  "sinking painting": "",
  "solemn painting": "",
  "tremendous statue": "",
  "twinkling painting": "",
  "valiant statue": "",
  "warm painting": "",
  "warrior statue": "",
  "wild painting left half": "",
  "wild painting right half": "",
  "wistful painting": "",
  "worthy painting": "",
};

export const artDescriptionKoMap: Record<ArtName, string> = {
  "academic painting": "",
  "amazing painting": "",
  "ancient statue": "",
  "basic painting": "",
  "beautiful statue": "",
  "calm painting": "",
  "common painting": "",
  "detailed painting": "",
  "dynamic painting": "",
  "familiar statue": "",
  "famous painting": "",
  "flowery painting": "",
  "gallant statue": "",
  "glowing painting": "",
  "graceful painting": "",
  "great statue": "",
  "informative statue": "",
  "jolly painting": "",
  "moody painting": "",
  "motherly statue": "",
  "moving painting": "",
  "mysterious painting": "",
  "mystic statue": "",
  "nice painting": "",
  "perfect painting": "",
  "proper painting": "",
  "quaint painting": "",
  "robust statue": "",
  "rock-head statue": "",
  "scary painting": "",
  "scenic painting": "",
  "serene painting": "",
  "sinking painting": "",
  "solemn painting": "",
  "tremendous statue": "",
  "twinkling painting": "",
  "valiant statue": "",
  "warm painting": "",
  "warrior statue": "",
  "wild painting left half": "",
  "wild painting right half": "",
  "wistful painting": "",
  "worthy painting": "",
};

export const artAuthenticityKoMap: Record<ArtName, string> = {
  "academic painting": "",
  "amazing painting": "",
  "ancient statue": "",
  "basic painting": "",
  "beautiful statue": "",
  "calm painting": "",
  "common painting": "",
  "detailed painting": "",
  "dynamic painting": "",
  "familiar statue": "",
  "famous painting": "",
  "flowery painting": "",
  "gallant statue": "",
  "glowing painting": "",
  "graceful painting": "",
  "great statue": "",
  "informative statue": "",
  "jolly painting": "",
  "moody painting": "",
  "motherly statue": "",
  "moving painting": "",
  "mysterious painting": "",
  "mystic statue": "",
  "nice painting": "",
  "perfect painting": "",
  "proper painting": "",
  "quaint painting": "",
  "robust statue": "",
  "rock-head statue": "",
  "scary painting": "",
  "scenic painting": "",
  "serene painting": "",
  "sinking painting": "",
  "solemn painting": "",
  "tremendous statue": "",
  "twinkling painting": "",
  "valiant statue": "",
  "warm painting": "",
  "warrior statue": "",
  "wild painting left half": "",
  "wild painting right half": "",
  "wistful painting": "",
  "worthy painting": "",
};

export const artTypeKoMap: Record<string, string> = {
  Painting: "그림",
  Statue: "조각",
};

export const artAvailabilityKoMap: Record<string, string> = {
  "Jolly Redd's Treasure Trawler": "",
};

const getFilledMapping = (
  map: Record<string, string>,
  key: string | undefined,
): string | undefined => {
  if (!key) return undefined;

  const mappedValue = map[key] ?? map[key.toLowerCase()];
  return mappedValue?.trim() ? mappedValue : undefined;
};

export const formatArtType = (type: string) => artTypeKoMap[type] ?? type;

export const formatArtAvailability = (availability: string | undefined) =>
  getFilledMapping(artAvailabilityKoMap, availability) ??
  availability ??
  "정보 없음";

export const formatArtOriginalTitle = (
  name: string,
  fallback: string | undefined,
) => getFilledMapping(artOriginalTitleKoMap, name) ?? fallback ?? "정보 없음";

export const formatArtAuthor = (name: string, fallback: string | undefined) =>
  getFilledMapping(artAuthorKoMap, name) ?? fallback ?? "정보 없음";

export const formatArtStyle = (name: string, fallback: string | undefined) =>
  getFilledMapping(artStyleKoMap, name) ?? fallback ?? "정보 없음";

export const formatArtDescription = (
  name: string,
  fallback: string | undefined,
) => getFilledMapping(artDescriptionKoMap, name) ?? fallback;

export const formatArtAuthenticity = (
  name: string,
  fallback: string | undefined,
) => getFilledMapping(artAuthenticityKoMap, name) ?? fallback;
